apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeehub-deployment
  namespace: employeehub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employehub
  template:
    metadata:
      labels:
        app: employehub
    spec:
      containers:
        - name: employeeshub
          image: docker.io/rajaaravindan2497/employeehub:875f30c
          imagePullPolicy: Always
          ports:
            - containerPort: 80