apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeehub-deployment
  namespace: employeehub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employehub
  template:
    metadata:
      labels:
        app: employehub
    spec:
      containers:
        - name: employeeshub
          image: docker.io/rajaaravindan2497/employeehub:875f30c
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres-service

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD