apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: employeehub-db-secret
  namespace: employeehub
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: employeehub/database
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: employeehub/database
        property: DB_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: employeehub/database
        property: DB_NAME